<?php
/** 
* cache.category.php
*
* @package    YIGECMS
* @author     
* @copyright  Copyright (c) 2008-2010  (http://www.YIGECMS.cn)
* @license    http://www.YIGECMS.cn/license.txt
   
*/

if (!defined('YIGECMS')) exit();

return array (
  0 => 
  array (
    'id' => '2',
    'module' => '',
    'parent_id' => '1',
    'title' => '行业动态',
    'biaozhi' => 'hangyedongtai',
    'html_url' => 'html/Article/gonsixinwen/index.html',
    'menu' => '1',
    'keyword' => '',
    'description' => '公司动态',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262410927',
    'update_time' => '1382262122',
  ),
  1 => 
  array (
    'id' => '14',
    'module' => 'Download',
    'parent_id' => '0',
    'title' => '下载模块',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '下载模块',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411171',
    'update_time' => '1342680191',
  ),
  2 => 
  array (
    'id' => '15',
    'module' => '',
    'parent_id' => '14',
    'title' => '系统软件',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '系统软件',
    'display_order' => '1',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411182',
    'update_time' => '1262411190',
  ),
  3 => 
  array (
    'id' => '1',
    'module' => 'Article',
    'parent_id' => '0',
    'title' => '文章模块',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '1',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  4 => 
  array (
    'id' => '17',
    'module' => '',
    'parent_id' => '14',
    'title' => '恢复类软件',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '恢复类软件',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411216',
    'update_time' => '0',
  ),
  5 => 
  array (
    'id' => '33',
    'module' => '',
    'parent_id' => '32',
    'title' => '首页横幅',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '首页横幅',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112629',
    'update_time' => '1267288982',
  ),
  6 => 
  array (
    'id' => '32',
    'module' => 'Ad',
    'parent_id' => '0',
    'title' => '广告模块',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '广告模块',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112377',
    'update_time' => '1267112406',
  ),
  7 => 
  array (
    'id' => '34',
    'module' => '',
    'parent_id' => '32',
    'title' => '公共',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '公共',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112648',
    'update_time' => '0',
  ),
  8 => 
  array (
    'id' => '35',
    'module' => 'Link',
    'parent_id' => '0',
    'title' => '链接类型',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '链接类型',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267287014',
    'update_time' => '0',
  ),
  9 => 
  array (
    'id' => '36',
    'module' => '',
    'parent_id' => '35',
    'title' => '默认类型',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '普通链接',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267287066',
    'update_time' => '1267288647',
  ),
  10 => 
  array (
    'id' => '104',
    'module' => '',
    'parent_id' => '103',
    'title' => '企业网站',
    'biaozhi' => 'qiyewangzhan',
    'html_url' => 'html/Product/shexiang/index.html',
    'menu' => '1',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1342668413',
    'update_time' => '1382252010',
  ),
  11 => 
  array (
    'id' => '99',
    'module' => '',
    'parent_id' => '72',
    'title' => '公司活动',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1324554041',
    'update_time' => '0',
  ),
  12 => 
  array (
    'id' => '103',
    'module' => 'Product',
    'parent_id' => '0',
    'title' => '产品模块',
    'biaozhi' => 'Product',
    'html_url' => '',
    'menu' => '1',
    'keyword' => '',
    'description' => '产品的跟分类',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1342668340',
    'update_time' => '1344836777',
  ),
  13 => 
  array (
    'id' => '98',
    'module' => '',
    'parent_id' => '1',
    'title' => '解决方案',
    'biaozhi' => 'jiejuefangan',
    'html_url' => 'html/Article/meitijujiao/index.html',
    'menu' => '1',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1324552052',
    'update_time' => '1382262069',
  ),
  14 => 
  array (
    'id' => '84',
    'module' => '',
    'parent_id' => '72',
    'title' => '员工天地',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1316584975',
    'update_time' => '1324554013',
  ),
  15 => 
  array (
    'id' => '94',
    'module' => '',
    'parent_id' => '93',
    'title' => '企业文化',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1316832672',
    'update_time' => '1324552285',
  ),
  16 => 
  array (
    'id' => '121',
    'module' => '',
    'parent_id' => '1',
    'title' => '公司新闻',
    'biaozhi' => 'gongsixinwen',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1382262138',
    'update_time' => '0',
  ),
  17 => 
  array (
    'id' => '122',
    'module' => 'Category',
    'parent_id' => '0',
    'title' => '关于我们',
    'biaozhi' => 'guanyu',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1382266166',
    'update_time' => '0',
  ),
  18 => 
  array (
    'id' => '123',
    'module' => '',
    'parent_id' => '122',
    'title' => '关于我们',
    'biaozhi' => 'guanyu',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1382266187',
    'update_time' => '0',
  ),
  19 => 
  array (
    'id' => '124',
    'module' => '',
    'parent_id' => '122',
    'title' => '服务项目',
    'biaozhi' => 'fuwu',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1382266204',
    'update_time' => '0',
  ),
);